blank_issues_enabled: true
contact_links:
  - name: Documentation
    url: https://github.com/maat-tools/maat/tree/main/docs
    about: Check the docs before opening an issue
  - name: Discussions
    url: https://github.com/maat-tools/maat/discussions
    about: Ask questions or share ideas here
